### ISSUE TITLE
why do not generate the file named "minion"

### ISSUE THREAD

**Issue by yangruichina** [alibaba/minion#3]
In the shell of ubuntu, after i run "python setup.py install", then i exect the cmd of "minion", but can not find it, could you tell me the reason.
Thank You.

**Comment by linxiulei** [comment]
setup.py would not install minion.py to $PATH. Just please try "python minion.py"

**Comment by yangruichina** [comment]
Thank you~

**Comment by yangruichina** [comment]
你好，这个是什么问题？
~/project/share/open_source/minion$ python minion.py
Traceback (most recent call last):
  File "minion.py", line 19, in <module>
    from peer.client import Minions
  File "/home/yangrui/project/share/open_source/minion/peer/client.py", line 21, in <module>
    from models import PieceFile, ExpireStorage, ExcThread
  File "/home/yangrui/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/yangrui/project/share/open_source/minion/peer/models.py", line 6, in <module>
    from utils import sizeof_fmt_human, md5sum
  File "/home/yangrui/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/yangrui/project/share/open_source/minion/peer/utils.py", line 15, in <module>
    from sendfile import sendfile as original_sendfile
  File "/home/yangrui/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named sendfile

**Comment by linxiulei** [comment]
I have pushed a new version, which updates doc, including that "pip install -r requirements.txt"
